# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'baiSi' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for baiSi
 pod 'AFNetworking', '~> 3.1.0'
 pod 'MJExtension', '~> 3.0.10'
 pod 'SDWebImage', '~> 3.7.6'
   pod 'SVProgressHUD', '~> 2.0.3'
 pod ‘UIView+AutoLayout’
pod 'DACircularProgress', '~> 2.3.1'

end
